/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.generated/wrangler.development.jsonc --env-file=.dev.vars.example --include-runtime=false --env-interface=CloudflareBindings apps/edge/worker-configuration.d.ts` (hash: 6ae3ac6c48554c848dcecbf9b7314432)
interface __BaseEnv_CloudflareBindings {
	BOARD_SNAPSHOTS: R2Bucket;
	BOARD_ASSETS: R2Bucket;
	WORKER_VERSION: WorkerVersionMetadata;
	ASSETS: Fetcher;
	APP_HOSTNAME: "localhost";
	BOARD_CREATION_ENABLED: "true";
	ALLOWED_ORIGINS: "http://localhost,http://localhost:4173,http://localhost:5173,https://127.0.0.1:8787";
	TURNSTILE_ENABLED: "false";
	ENVIRONMENT: "development";
	TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
	BOARD_ROOMS: DurableObjectNamespace<import("./src/gateway").BoardRoom>;
	ORGANISATION_ROOMS: DurableObjectNamespace<import("./src/gateway").OrganisationRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/gateway");
		durableNamespaces: "BoardRoom" | "OrganisationRoom";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_HOSTNAME" | "BOARD_CREATION_ENABLED" | "ALLOWED_ORIGINS" | "TURNSTILE_ENABLED" | "ENVIRONMENT" | "TURNSTILE_SITE_KEY">> {}
}
